name: deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core 3
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
     
      - name: Run Tests
        run:  dotnet test --nologo

      - name: Generate Release
        run: dotnet publish src/AzureFunctionsExample.Function --configuration Release --output ./out

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy Azure Function"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.FUNCTION_NAME }}
          package: ./out